### ISSUE TITLE
New cofh api

### ISSUE THREAD

**Issue by grydian** [Nauktis/SolarFlux#12]
Since the new cofh api I cant get the solars to power EnderIO machines directly anymore.  I have have to use a cable to connect the solars to the farming station.  Be the updates to cofhcore and enderio it was working perfectly.   Just wanted to let you know..  Thanks for a great mod.

**Comment by grydian** [comment]
Just to let you know I tested again with the latest solarflux .5a and I also updated cofh core to b9-71.  That was the absolute latest I could find.  I also updated all the teamcofh mods to the latest betas I could find and I still have to use a conduit to power machines directly with the solar panels.  Thanks for all your help man.

**Comment by Barhandar** [comment]
[You're checking for the `IEnergyHandler`](https://github.com/Nauktis/SolarFlux/blob/master/src/main/java/com/nauktis/solarflux/blocks/SolarPanelTileEntity.java#L103), which isn't used by machines anymore, only various energy cells. You need to check for `IEnergyReceiver` instead to make it work with major mods. Presumably it shouldn't break compatibility with Mekanism and GC, because Handler extends both Provider and Receiver, but just to be on safe (if not sane) side you could just check for both Handler and Receiver.

**Comment by Nauktis** [comment]
@Barhandar Damn I should have seen your message earlier.
Thanks for reporting man. I just pushed a fix ;)
