### ISSUE TITLE
Update Wipes All Old Solar Panels...

### ISSUE THREAD

**Issue by KaneHart** [Nauktis/SolarFlux#20]
Looks like you went from the base solar panel as SolarFlux:solar1 to SolarFlux:solar0 and this has caused the solar panels to wipe or at least for sure the current top tier.

I'm hoping you will correct this as you are wiping everyone's solar panels in existence.

**Comment by Nauktis** [comment]
This is indeed an unfortunate but expected behaviour when migrating from version 0.5x to version 0.6x

As you correctly guessed, tiers are now numbered from 0 and not 1.
This causes all existing solar panels to gain one level and the last tier of panels to be removed from the world.
The migration also sometimes requires to break and place back down existing solar panels with a pickaxe to have them properly generate energy again.

Those side effects are due to the amount of code that changed from 0.5x to 0.6x.
Is this migration really unmanageable on your server? This of course will happen only once (first time loading the world after migrating) and should not happen again in future releases.

**Comment by KaneHart** [comment]
Well the biggest issue is Tier 6 Solar Panels go missing. I had no time to check 1-5 as I reverted our backup and went back to 0.5 instantly. I assume if someone has tier 5 before they have a tier 6 and tier 6 since there is no tier 6 would be removed. Or maybe they all are removed. 

I will have to do more testing later on but I myself will have to stay with 0.5 for now as it's hard to manage many dozens of players solar panels and try to replace each one let alone having to play the honesty card.

**Comment by Nauktis** [comment]
I understand. I'll try to see if I can release a new version that is more friendly for people migrating from version 0.5.

I have an idea in mind and I'll test it out tonight. I'll keep you posted.

**Comment by Nauktis** [comment]
Just pushed a new version on Curse (0.6b)
IDs of solar panels are back to what they were so the migration from version 0.5x should go a lot smoother.
Worst case scenario, you will only need to ask people to break their solar panels with a pickaxe and put them back down so that the energy generation behaves properly.

Please let me know if you find any other issue regarding the migration or the new version of the mod.

N.
